name: Daily Stock Tracker

on:
  schedule:
    - cron: '0 1 * * *'  # Schedule: Runs daily at 8:00 AM UTC
  workflow_dispatch:     # Allow manual runs

jobs:
  run-stock-tracker:
    runs-on: ubuntu-latest  # Runner environment (Linux-based)

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install required Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the Python Script with Secrets
      - name: Run Stock Tracker
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python tracker.py
